catatsuy/notify_slack

- cli/cli.go
When notify_slack runs as non-root user A and it reads stdin from another non-root user, it fails with permission denied error.
```
$ id -un
nonroot1
$ ps aux | sudo -u nonroot2 notify_slack -snippet
open /dev/stdin: permission denied
```
This is probably because `nonroot2` user does not have read right for the pipe. (Sorry I couldn't find documentation about this behavior)
```
$ echo hello | sudo -u nonroot2 bash -c 'ls -l /dev/stdin; ls -l /proc/self/fd/0"'
lrwxrwxrwx 1 root root 15 May 17 15:03 /dev/stdin -> /proc/self/fd/0
lr-x------ 1 nonroot2 nogroup 64 Jul  3 17:47 /proc/self/fd/0 -> 'pipe:[164455751]'
```
This patch fixes this error because `os.Stdin` is just fd 0.
> Read stdin via os.Stdin instead of /dev/stdin to avoid permission error.

- .github/workflows/go.yml
- cli/cli.go
- throttle/exec.go
- throttle/exec_test.go
make exec.Start() functions synchronous
callback functions should not be killed by context
> refactor exec.Start() and don't provide context for callback

- slack/client.go
The slack client response body did not seem to be closed.
please take it in, If you don't mind.
I'm going to use at ISUCON12. Thank you for your software.
> [nits] close response body

- cli/cli.go
- throttle/exec.go
- throttle/exec_test.go
Before, no context for Slack because we want it to run even if cancel. Now, I give WithoutCancel context clearly.
> Change: Give WithoutCancel context for Slack request

- cli/cli.go
- go.mod
- go.sum
This pull request primarily focuses on improving the user experience and dependencies management in the `cli/cli.go` and `go.mod` files respectively. The most significant changes include the addition of a new package in the import statements, a new condition in the `Run` function to handle terminal input, and the inclusion of new dependencies in the `go.mod` file.
Changes to `cli/cli.go`:
* Imported the `golang.org/x/term` package to handle terminal inputs.
* Added a condition in the `Run` function to check if the input is from a terminal and return an error if no input file is specified.
Changes to `go.mod`:
* Added `golang.org/x/sys` and `golang.org/x/term` as indirect dependencies to the project.
> Add check for input file in CLI Run method

- .github/workflows/go.yml
- .github/workflows/release.yml
This pull request includes changes to the Go version and the GoReleaser arguments in the GitHub workflow files. The Go version has been updated from 1.21.x to 1.22.x in both the `go.yml` and `release.yml` files. The arguments for the GoReleaser action have also been modified in the `release.yml` file.
* [`.github/workflows/go.yml`](diffhunk://#diff-678682767f2477de3e3c546746f8568b9a1942b2c647d32331d7e774b8ff8d9fL9-R9): Updated the Go version in the matrix from 1.21.x to 1.22.x.
* [`.github/workflows/release.yml`](diffhunk://#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34L15-R20): Updated the Go version from 1.21.x to 1.22.x and changed the GoReleaser arguments from `release --rm-dist` to `release --clean`.
> Update Go versions to 1.22.x in workflows

- Makefile
This pull request includes changes to the `Makefile` to improve code coverage reporting. A new `cover` target has been added to the `Makefile` which generates a coverage report and opens it in a browser.
* [`Makefile`](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R29-R33): Added a `cover` target to the `Makefile` that runs tests with coverage and then uses `go tool cover` to generate and display an HTML coverage report.
> Add cover target to run tests with coverage

- internal/cli/cli.go
- internal/slack/client.go
- internal/slack/client_test.go
This pull request introduces changes to the `internal/cli/cli.go`, `internal/slack/client.go`, and `internal/slack/client_test.go` files. The major changes include the addition of a debug mode in the CLI, switching from the standard log package to the structured log package (slog), and updating the tests to reflect these changes.
Changes to the CLI (`internal/cli/cli.go`):
* Imported the `log/slog` package for structured logging.
* Added a `debugMode` boolean variable to the `Run` function. [[1]](diffhunk://#diff-223a11f450a34cbbac0fdfc3e1f9caeefd948071a628813149e6f8aa7c2bc15eR64) [[2]](diffhunk://#diff-223a11f450a34cbbac0fdfc3e1f9caeefd948071a628813149e6f8aa7c2bc15eR84-R85)
* Created a new `slog.Logger` instance based on the `debugMode` variable.
* Updated the `NewClientForPostFile` and …
> Add debug mode with slog for logging

- internal/cli/cli.go
- internal/cli/cli_test.go
- internal/slack/client.go
- internal/slack/client_test.go
This pull request primarily focuses on refactoring the handling of Slack tokens in the codebase, specifically in the `internal/cli/cli.go`, `internal/cli/cli_test.go`, `internal/slack/client.go`, and `internal/slack/client_test.go` files. The changes include moving the Slack token from function parameters to a field in the `Client` struct, and adjusting all related function calls and tests to match this new structure.
Changes to Slack token handling:
* [`internal/cli/cli.go`](diffhunk://#diff-223a11f450a34cbbac0fdfc3e1f9caeefd948071a628813149e6f8aa7c2bc15eL143-R150): The Slack token is now checked before creating a new Slack client, and the client is created with the token as a parameter. The token is no longer passed as a parameter to the `PostFile` method. …
> Refactor slack token validation and usage in CLI and Slack client

- CHANGELOG.md
- README.md
- internal/cli/cli.go
- internal/cli/cli_test.go
- internal/config/config.go
- internal/config/config_test.go
- internal/config/testdata/config_deprecated.toml
- internal/slack/client.go
- internal/slack/client_test.go
- internal/slack/export_test.go
refs: #148 
This pull request introduces significant changes to the Slack API implementation, including updates to the file upload process and changes to the command line interface (CLI) and configuration files. The most important changes are the deprecation of the `files.upload` API, the introduction of new APIs for file uploads, and the replacement of the `channel` parameter with `channel-id` for file uploads.
API Changes:
* [`CHANGELOG.md`](diffhunk://#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR3-R16): The `files.upload` API is now deprecated and replaced with `files.getUploadURLExternal` and `files.completeUploadExternal`. The `channel` parameter for file uploads has been replaced with `channel-id`. The `-filetype` option has been modified and replaced with …
> use new api for uploading file

- README.md
This pull request includes minor modifications to the `README.md` file to improve the clarity of the documentation. The changes primarily focus on enhancing the readability of the notes section and emphasizing important information for users.
Key changes:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L107-R107): The "Note" section has been reformatted for better readability and emphasis. The line "if you need to post a file public, you must specify `channel_id`" has been bolded to highlight its importance. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L107-R107) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L117-R117)
> Update Slack API note in README.md

- go.mod
This pull request primarily updates the Go version and modifies the dependencies in the `go.mod` file. The Go version is updated from 1.19 to 1.22.2. The dependency `github.com/google/go-cmp` is moved from an indirect requirement to a direct one, while the indirect requirement for `golang.org/x/sys` is retained.
Here's the key change:
* [`go.mod`](diffhunk://#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L3-R11): Updated the Go version from 1.19 to 1.22.2. Moved `github.com/google/go-cmp` from an indirect requirement to a direct one, and retained `golang.org/x/sys` as an indirect requirement.
> Update go version to 1.22.2 and add go-cmp dependency

- CHANGELOG.md
This pull request includes a minor update to the `CHANGELOG.md` file. The change specifies the required Go version as 1.22.2 or higher.
> Update Go version requirement to 1.22.2 or higher

- CHANGELOG.md
This pull request includes changes to the `CHANGELOG.md` file, primarily introducing a new `-debug` option for development purposes.
The key change is:
* [`CHANGELOG.md`](diffhunk://#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR12-R15): A new `-debug` option has been added for development. This option will help developers in debugging the application.
> Add new `-debug` option for development

- .github/workflows/release.yml
This pull request includes a small but important change to the `.github/workflows/release.yml` file. The `go-version` in the `Setup Go` job has been updated from a wildcard version `1.22.x` to a specific version `1.22.4`. This change ensures that the build process uses a consistent version of Go, improving the reliability of the build.
> Update Go version in GitHub Actions workflow to 1.22.4

- renovate.json
This pull request includes a change to the `renovate.json` file. The change adds a new section in the file that matches the `.github/workflows/release.yml` file and uses the `golang-version` data source template. The `depNameTemplate` is set to `golang` and the `matchStrings` is set to match the `go-version` followed by a version number.
> Add release.yml to renovate.json for golang version updates

- .github/workflows/go.yml
This pull request includes a minor update to the Go version used in the GitHub Actions workflow configuration.
* [`.github/workflows/go.yml`](diffhunk://#diff-678682767f2477de3e3c546746f8568b9a1942b2c647d32331d7e774b8ff8d9fL9-R9): Updated the Go version from `1.22.x` to `1.23.x`.
> Update Go version in GitHub Actions workflow from 1.22.x to 1.23.x

- go.mod
This pull request updates the Go version in the `go.mod` file to ensure compatibility with the latest features and improvements.
* [`go.mod`](diffhunk://#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L3-R3): Updated the Go version from `1.22.2` to `1.23.0` to leverage new language features and improvements.
refs: https://go.dev/doc/go1.23#timer-changes
> update Go version from 1.22.2 to 1.23.0 in go.mod

- README.md
This pull request updates the `README.md` file to provide clearer instructions on obtaining a Slack API token. The main change simplifies the token creation instructions by linking directly to the official Slack guide.
Documentation updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L120-R126): Simplified the section on obtaining a Slack API token by removing detailed steps and providing a link to the official Slack guide.
> Update README to improve instructions for obtaining Slack API token

- internal/cli/cli.go
This pull request includes changes to the `Run` method in `internal/cli/cli.go` to ensure a consistent context is used throughout the method. This helps maintain context propagation and improves the manageability of context-related operations.
Context management improvements:
* [`internal/cli/cli.go`](diffhunk://#diff-223a11f450a34cbbac0fdfc3e1f9caeefd948071a628813149e6f8aa7c2bc15eR145-R146): Introduced a `ctx` variable initialized with `context.Background()` at the beginning of the `Run` method to ensure a consistent context is used.
* [`internal/cli/cli.go`](diffhunk://#diff-223a11f450a34cbbac0fdfc3e1f9caeefd948071a628813149e6f8aa7c2bc15eL157-R159): Updated the call to `uploadSnippet` to use the newly created `ctx` variable instead of creating a new context.
* …
> Use a shared context for uploading snippets and signal handling in CLI.

- .github/workflows/go.yml
- go.mod
- internal/cli/cli_test.go
- internal/slack/client_test.go
- internal/throttle/exec_test.go
This pull request includes several updates to the Go version and refactors tests to use the testing context. The most important changes include updating the Go version in the workflow and module files, and refactoring multiple test files to replace `context.Background()` with `t.Context()`.
* [`.github/workflows/go.yml`](diffhunk://#diff-678682767f2477de3e3c546746f8568b9a1942b2c647d32331d7e774b8ff8d9fL9-R9): Updated the Go version from `1.23.x` to `1.24.x` in the CI workflow.
* [`go.mod`](diffhunk://#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L3-R3): Updated the Go version from `1.23.0` to `1.24.0`.
* [`internal/cli/cli_test.go`](diffhunk://#diff-246ca99ef259ecd53ea453c8ddbb8893f3caf9cbc11a91bcc838daccd21c94ddL53-R53): Refactored the `TestUploadSnippet` function …
> use t.Context() instead of context.Background() for test

- .github/workflows/go.yml
This pull request updates the GitHub Actions workflow for Go. The most important changes include simplifying the workflow configuration by removing the matrix strategy and hardcoding the Go version.
Workflow configuration simplification:
* [`.github/workflows/go.yml`](diffhunk://#diff-678682767f2477de3e3c546746f8568b9a1942b2c647d32331d7e774b8ff8d9fL5-R10): Removed the matrix strategy and hardcoded the Go version to `1.24.0` instead of using a matrix variable.
> Update Go version to 1.24.0 in GitHub Actions workflow configuration.

- renovate.json
This pull request includes an update to the `renovate.json` configuration file to ensure proper dependency management for Go versions in GitHub workflows.
Changes to dependency management:
* [`renovate.json`](diffhunk://#diff-7b5c8955fc544a11b4b74eddb4115f9cc51c9cf162dbffa60d37eeed82a55a57R16-R25): Added a new configuration block to match and update Go versions specified in the `.github/workflows/go.yml` file. This includes setting the `datasourceTemplate` to "golang-version" and defining the `depNameTemplate` as "golang".
> Add golang version datasource configuration for go.yml workflow

- go.mod
- internal/throttle/exec.go
- internal/throttle/exec_test.go
- Keep refs to io.ReadCloser/*io.PipeReader in Exec.
- On ctx.Done(), close the reader (CloseWithError for PipeReader).
- Add cancelReader and call it before doneCallback.
- Replace time.Sleep with synctest.Wait and wrap tests with synctest.Test.
Prevents hangs/leaks on blocked ReadLine and removes test flakiness.
This pull request improves the handling of context cancellation and resource cleanup in the `Exec` struct, especially when working with pipe readers. It also updates the related tests to be more reliable and deterministic by using the `synctest` package.
**Resource management and context cancellation:**
- Enhanced the `Exec` struct to track `io.ReadCloser` and `io.PipeReader` instances, allowing for proper closure and cleanup when context is cancelled. The new `cancelReader` …
> Unblock ReadLine on context cancel

- internal/cli/cli.go
This pull request refactors the `CLI` implementation in `internal/cli/cli.go` to improve maintainability and clarity by modularizing the flag parsing, configuration loading, and execution logic. The main `Run` method is simplified, and new helper methods and a struct are introduced to encapsulate CLI options and logic. This makes the codebase easier to understand, extend, and test.
Key changes include:
**Refactoring and Code Structure:**
* Introduced a new `cliOptions` struct to encapsulate all CLI flag values, replacing multiple local variables and streamlining option handling.
* Split the monolithic `Run` method into smaller, focused helper methods: `parseFlags`, `setupFlags`, `processArguments`, `printVersion`, `loadConfiguration`, `createLogger`, `handleSnippetMode`, `handleTextMode`, …
> refactor CLI Run to use structured flag parsing and separate modes

- internal/throttle/exec.go
This pull request refactors the `Exec` struct and its related logic in `internal/throttle/exec.go` to improve code clarity, robustness, and thread safety. The main changes include restructuring the reading and flushing logic, improving resource cleanup, and making buffer operations thread-safe.
**Refactoring and code structure improvements:**
* Rewrote the `Exec` struct to clarify its responsibilities, replacing ambiguous fields (`writer`, `exitC`) with clearer ones (`buffer`, `done`), and adding documentation for key methods and struct fields.
* Refactored the reading and flushing logic: reading from input and periodic flushing are now separated into `readInput` (background goroutine) and `processEvents` (main event loop), improving maintainability and correctness.
* Made buffer …
> refactor Exec to read input in background, buffer lines, flush on interval

- cmd/output/main.go
This pull request updates the random number generation in `cmd/output/main.go` to use the newer `math/rand/v2` package and its API. The seeding logic has also been removed, as the new API handles seeding automatically.
**Dependency and API updates:**
* Switched import from `math/rand` to `math/rand/v2` and updated usage from `rand.Intn` to `rand.IntN`, reflecting the new package's API.
**Code cleanup:**
* Removed manual seeding of the random number generator, as `math/rand/v2` now manages this internally.
> update random import to rand/v2 and fix sleep duration calculation

- .github/workflows/go.yml
- .github/workflows/release.yml
- .github/workflows/security.yml
This pull request updates GitHub Actions workflow configuration files to explicitly set permissions for better security and access control. The most important changes are the addition of `permissions` blocks to each workflow, specifying the minimum required access for each job.
**Workflow permissions updates:**
* Added `permissions: contents: read` to `.github/workflows/go.yml` to restrict the workflow's access to repository contents to read-only.
* Added `permissions: contents: write` to `.github/workflows/release.yml` to allow the release workflow to write to repository contents, which is necessary for publishing releases.
* Added `permissions: contents: read` to `.github/workflows/security.yml` to restrict the security workflow's access to repository contents to read-only.
> Add explicit contents permissions to GitHub workflow files for security
